apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  REACT_APP_API_URL: "https://dev.oppsdev.xyz/api"
  REACT_APP_ENV: "development"
  REACT_APP_LOG_LEVEL: "debug"
  VITE_FIREBASE_API_KEY: "AIzaSyAugTSDXrvUMqMjh4nAzMSgitrBEP8nO24"
  VITE_FIREBASE_AUTH_DOMAIN: "langchain-project-ea742.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "langchain-project-ea742"
  VITE_FIREBASE_STORAGE_BUCKET: "langchain-project-ea742.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID: "506724991827"
  VITE_FIREBASE_APP_ID: "1:506724991827:web:ab62a9675453b1a74a17a6"
