apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-analyzer-dev


patchesStrategicMerge:
- deployment.yaml
- configmap.yaml
- hpa.yaml

commonLabels:
  environment: dev

images:
- name: <REGISTRY>/invoice-analyzer-frontend
  newName: 889039329094.dkr.ecr.us-west-2.amazonaws.com/invoice-analyzer-frontend
  newTag: "29"
resources:
- ../../../base/frontend
