apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-analyzer-prod

bases:
  - ../../../base/frontend

patchesStrategicMerge:
  - deployment.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  environment: prod

images:
  - name: invoice-analyzer-frontend
    newName: 889039329094.dkr.ecr.us-west-2.amazonaws.com/invoice-analyzer-frontend
    newTag: latest
