apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - external-secret.yaml
  - hpa.yaml
  - servicemonitor.yaml
  - migration-job.yaml

commonLabels:
  app: invoice-analyzer
  component: backend
