apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../dev/monitoring
  - secretstore.yaml

namespace: monitoring

patches:
  # Fix Grafana PVC storage class
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: standard
    target:
      kind: PersistentVolumeClaim
      name: grafana-storage