apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator-deployment.yaml
  - operator-rbac.yaml
  - operator-service.yaml
  - secretstore.yaml
  - serviceaccount.yaml

commonLabels:
  app: external-secrets
