apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

bases:
  - ../../../base/crds
  - ../../../base/monitoring/prometheus-operator
  - ../../../base/monitoring/grafana
  - ../../../base/monitoring/node-exporter
  - ../../../base/monitoring/kube-state-metrics

commonLabels:
  environment: prod
