apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

bases:
  - ../../../base/monitoring/prometheus-operator
  - ../../../base/monitoring/grafana

commonLabels:
  environment: prod
