apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml
  - external-secret.yaml
  - pvc.yaml
  - podmonitor.yaml

commonLabels:
  app: invoice-analyzer
  component: database
