apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  FIREBASE_PROJECT_ID: "langchain-project-ea742"
  FIREBASE_CLIENT_EMAIL: "firebase-adminsdk-fbsvc@langchain-project-ea742.iam.gserviceaccount.com"
  CORS_ORIGINS: "https://oppsdev.xyz"
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "40"
  AWS_REGION: "us-west-2"
  S3_BUCKET_NAME: "invoice-analyzer-prod-uploads"
