apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-analyzer-prod

bases:
  - ../../../base/backend

patchesStrategicMerge:
  - deployment.yaml
  - configmap.yaml
  - hpa.yaml
  - serviceaccount.yaml

commonLabels:
  environment: prod

images:
  - name: invoice-analyzer-backend
    newName: 889039329094.dkr.ecr.us-west-2.amazonaws.com/invoice-analyzer-backend
    newTag: latest
