apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-analyzer-prod

bases:
  - ../../../base/backend

patchesStrategicMerge:
  - deployment.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  environment: prod
