apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  # Prometheus Operator resources (must be deployed first)
  - operator-rbac.yaml
  - operator-deployment.yaml
  - operator-service.yaml
  # Prometheus instance resources
  - rbac.yaml
  - prometheus.yaml
  - service.yaml
  - configmap.yaml
  - prometheusrule.yaml

commonLabels:
  app: prometheus
