apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheus.yaml
  - service.yaml
  - rbac.yaml
  - configmap.yaml
  - prometheusrule.yaml

commonLabels:
  app: prometheus
