apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheusrule-crd.yaml
  - servicemonitor-crd.yaml
  - prometheus-crd.yaml
  - podmonitor-crd.yaml
  - externalsecret-crd.yaml
  - secretstore-crd.yaml
  - clustersecretstore-crd.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
