apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-analyzer-prod

resources:
  - namespace.yaml
  - backend
  - database
  - frontend
  - ingress
  - monitoring
  - network-policies
  - rbac
  - storage

commonLabels:
  environment: prod
  app: invoice-analyzer
  managed-by: argocd
