apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces/invoice-analyzer-prod.yaml
  - frontend
  - backend
  - database
  - ingress
  - monitoring
  - rbac
  - network-policies
  - external-secrets

commonLabels:
  environment: prod
  managed-by: argocd

