apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-analyzer-prod

bases:
  - ../../../base/ingress

patchesStrategicMerge:
  - ingress.yaml

commonLabels:
  environment: prod
