apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-analyzer-dev

bases:
  - ../../../base/ingress

patchesStrategicMerge:
  - ingress.yaml

commonLabels:
  environment: dev
