apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - external-secret.yaml
  - configmap-dashboards.yaml
  - ingress.yaml

commonLabels:
  app: grafana

configMapGenerator:
  - name: grafana-dashboards-standard
    files:
      - dashboards/node-exporter-full.json
      - dashboards/k8s-cluster.json
