apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces/invoice-analyzer-dev.yaml
  - frontend
  - backend
  - database
  - ingress
  - monitoring
  - rbac
  - network-policies

commonLabels:
  environment: dev
  managed-by: argocd

