apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invoice-analyzer-dev

resources:
  - namespace.yaml
  - external-secrets
  - backend
  - database
  - frontend
  - ingress
  - network-policies
  - rbac

commonLabels:
  environment: dev
  app: invoice-analyzer
  managed-by: argocd
